export enum Commune {
  Bandalungwa ='Bandalungwa',
  Barumbu = 'Barumbu',
  Bumbu = 'Bumbu',
  Gombe = 'Gombe',
  KasaVubu = 'Kasa-Vubu',
  Kimbanseke = 'Kimbanseke',
  Kinshasa = 'Kinshasa',
  Kintambo = 'Kintambo',
  Kisenso = 'Kisenso',
  Lemba = 'Lemba',
  Limete = 'Limete',
  Lingwala = 'Lingwala',
  Makala = 'Makala',
  Maluku= 'Maluku',
  Masina = 'Masina',
  Matete= 'Matete',
  MontNgafula = 'Mont-Ngafula',
  Ndjili = 'Ndjili',
  Ngaba = 'Ngaba',
  Ngaliema = 'Ngaliema',
  NgiriNgiri = 'Ngiri-Ngiri',
  Nsele = 'Nsele',
  Selembao = 'Selembao'
}
